#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Console\Crafter;

$command = $_SERVER['argv'][1] ?? null;

$handler = new Crafter();
$handler->run($command, array_slice($_SERVER['argv'], 2));
